### ISSUE TITLE
Question: How to manage users on self-hosted system?

### ISSUE THREAD

**Issue by ngraf** [pixeleye-io/pixeleye#331]
Given I started a self-hosted pixel-eye instance following the guide at https://pixeleye.io/docs/guides/self-hosting
When I open http://localhost:3000/ I get asked to create an account.

I wonder if the intention is that user management works exactly the same like on pixeleye.io.
I'd rather like to skip the whole user management, since I will share this self-hosted instance just with my colleagues.
If user management is intended, then how how do I enable the PixelEye to send out verification e-mails?
I have the impression this is not a functional feature of the default self-hosted configuration?

Well, in the end I am just asking for more documentation in https://pixeleye.io/docs/guides/self-hosting what my options are to set up a functional user management in self-hosted scenario.

**Comment by AlfieJones** [comment]
Yeah we use the exact same management as on Pixeleye.io. 

You can actualy disable the verification page by removing this https://github.com/pixeleye-io/pixeleye/blob/main/docker/config/template.kratos.yml#L47C1-L52C68

But this will mean manually inviting users won't work.

To get it all working, you'll need an smtp server up and to change https://github.com/pixeleye-io/pixeleye/blob/main/docker/config/template.kratos.yml#L104 along with https://github.com/pixeleye-io/pixeleye/blob/main/docker/docker-compose-self-hosting.yml#L100-L102

**Comment by AlfieJones** [comment]
The self hosted docker compose comes with oryd/mailslurper:latest-smtps pre-configured so you can also use that to monitor the emails sent. 

It's exposed on ports "4436" & "4437" (I forget which is the managment ui)

Anyone with access to this management ui would be able to reset anyones passwords but in a private environment it should be fine

**Comment by sschneider-ihre-pvs** [comment]
I didn't even managed to get self hosting to work. it is blocked by the kratos container not having `/etc/config/kratos/kratos.yml` not a file or directory

**Comment by AlfieJones** [comment]
@sschneider-ihre-pvs  Have you copied the config directory from https://github.com/pixeleye-io/pixeleye/tree/main/docker/config ?

**Comment by hinogi** [comment]
> @sschneider-ihre-pvs Have you copied the config directory from https://github.com/pixeleye-io/pixeleye/tree/main/docker/config ?

you mean, manually into the docker container?

**Comment by AlfieJones** [comment]
You just need it alongside the compose file. You can see examples of where the docker-compose accesses files inside the config e.g https://github.com/pixeleye-io/pixeleye/blob/main/docker/docker-compose-self-hosting.yml#L24C1-L24C24

**Comment by hinogi** [comment]
well I started from the docker folder with `docker-compose -f docker-compose-self-hosting.yml up -d` and kratos never worked

**Comment by AlfieJones** [comment]
Could you post your logs?

**Comment by sschneider-ihre-pvs** [comment]
```
Error: open /etc/config/kratos/kratos.yml: no such file or directory
Usage:
  kratos serve [flags]
Flags:
  -c, --config strings   Path to one or more .json, .yaml, .yml, .toml config files. Values are loaded in the order provided, meaning that the last config file overwrites values from the previous config file.
      --dev              Disables critical security features to make development easier
  -h, --help             help for serve
      --sqa-opt-out      Disable anonymized telemetry reports - for more information please visit https://www.ory.sh/docs/ecosystem/sqa
      --watch-courier    Run the message courier as a background task, to simplify single-instance setup
open /etc/config/kratos/kratos.yml: no such file or directory
```

**Comment by AlfieJones** [comment]
Ahh, the file had been renamed, The latest ./config dir should work now

**Comment by hinogi** [comment]
still doesn't work. Also, the url setting are stored in two places, the docker yml and the kratos yml

**Comment by hinogi** [comment]
```
Application error: a server-side exception has occured (see server logs for more information)
```

**Comment by hinogi** [comment]
Status 403

**Comment by hinogi** [comment]
Seems to be an issue with using service names for urls via intranet network

**Comment by hinogi** [comment]
even changing the urls does not make it work

**Comment by hinogi** [comment]
Backend always tries to connect to rabbitmq via localhost and fails.

**Comment by AlfieJones** [comment]
What machine are you using? It seems to work fine for me on both windows and linux

**Comment by hinogi** [comment]
That would be a Ubuntu server

**Comment by hinogi** [comment]
I changed ports in the docker file to avoid port collision but that seems to be not expected by the whole setup

**Comment by AlfieJones** [comment]
Would it be possible to share all the logs?

**Comment by hinogi** [comment]
that are a lot of logs from a lot of containers I guess?!

**Comment by AlfieJones** [comment]
I can't really help any more unless I can see them
